### PR TITLE
use raw rbw output and parse json

### PR DESCRIPTION
**Pull request by mindrunner**
Enable additional fields for secure notes as previously discussed.

https://github.com/fdw/rofi-rbw/issues/66

https://github.com/doy/rbw/issues/101

https://github.com/doy/rbw/pull/97

### CODE REVIEW

**Comment by mindrunner** [comment]
needs some more work

**Comment by benedikt-bartscher** [comment]
Maybe we can make rofi-rbw cleaner, faster and more flexible by completly switching to json with https://github.com/doy/rbw/issues/107

**Comment by fdw** [comment]
Hey, thanks for showing me `--json` and starting an implementation! I'm looking forward to your ideas, @mindrunner 🙂

But I don't think json will be faster, @benedikt-bartscher. Just cleaner and more robust 😉

**Comment by fdw** [comment]
@mindrunner, what's the plan here? Do you want to keep working on this? Should I take over?

**Comment by mindrunner** [comment]
Sorry, I kinda forgot about it. I use a local install with the changes from this PR and it works quite nicely for me. Of course, there could be done much more improvement, but I did not find any time so far. Probably because there is no pressure for me currently, since I am much more happy than with my previous solution.

Would you like to take over and move this one level further? Then go ahead :) If not, what would be missing if we want to merge this?

**Comment by fdw** [comment]
To be honest, I thought you had plans, since this is still a draft. If you have any ideas, feel free to either push them or share them here 🙂

Also, I'll have a look at it when I find some time.

**Comment by mindrunner** [comment]
Yeah probably my bad due to lack of communication. I don't really remember why I kept it on draft. Something was not working intuitively. I think a custom field must not be named `password` because it creates confusion with the password field. Bu I am not sure. I just found workarounds for myself. Would love to see the functionality upstream, tho.

**Comment by fdw** [comment]
I've pushed something to `read-from-json`. It would be very nice if someone besides me could try that.

**Comment by mindrunner** [comment]
Codewise looks nice. :) Did not try it yet

**Comment by mindrunner** [comment]
`data["data"]` can be `None`

This works better for me:

```
            def get_data(d, key):
                if d["data"] is not None and key in d["data"]:
                    return d["data"][key]
                return None

            return Credentials(
                entry.name,
                entry.folder,
                entry.username,
                get_data(data, "password"),
                get_data(data, "totp") is not None,
                [item["uri"] for item in get_data(data, "uris")] if get_data(data, "uris") is not None else [],
                {item["name"]: item["value"] for item in data["fields"]},
            )
```

**Comment by fdw** [comment]
How did you manage to get an empty `data`? Was that a login type or something else?

**Comment by fdw** [comment]
Thank you 🙂
I've decided on another approach, as I don't want to check every single property. And I don't think `rofi-rbw` has ever sensibly worked with anything but logins, has it?

**Comment by benedikt-bartscher** [comment]
Hey guys, thanks for your work on this one.
@fdw i just installed the read-from-json branch on my machine. Works flawless so far, i will report back if smth goes wrong :)

**Comment by mindrunner** [comment]
I still see the issue where you cannot copy/type data from a custom field named 'password', even though it is visible.

Steps to reproduce:

- Create login entry, leave password empty
- add custom field with name `password`
- try to copy the custom data

Result: empty clipboard
Expected: custom data in clipcoard

**Pull request closed without merging**
