### PR TITLE
sort entries by use for rofi, fix #79

### LINKED ISSUE #79: rofi history
Hi,

With wofi, the first entries shown are the one recently used, which is super convenient. But with rofi, this is not possible, as we are using dmenu mode, and this won't be implemented there: https://github.com/davatorium/rofi/issues/747.

Therefore, I suggest to implement this in rofi-rbw, and maintain a simple history file in cache, as what rofi is already using, eg:
```
$ cat ~/.cache/rofi-3.runcache
18 thunderbird
17 firefox
3 pavucontrol
```

For my current use cases, I guess `{n} {entry.folder}/{entry.name}\n` would be enough, and I can provide a PR for this.
But if anybody has better ideas before that, please don't hesitate !

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

Here is a fix for #79, which is simple and working for me.

It would break when `Selector._calculate_max_width` would change, though. Please tell me if we should do this in another way.

### CODE REVIEW

**Comment by nim65s** [comment]
Well, actually, if we can `.format()` and `.parse()` entries, cache become more robust to `max_width` changes.

**Comment by fdw** [comment]
First, many thanks for the PR! 🙂

I've thought a bit about the whole topic, and while I like the general idea, I'd like some changes in the implementation:
- First, formatting should be stay a responsibility of the selector. We might get a new one with different formatting requirements, and then the entry would need `format_common` and `format_new`. That doesn't sound good to me.
- More importantly, just like you wondered above, I'd like to keep the cache file independent of formatting.
- And finally, and most importantly, the cache file must not leak sensitive information! While it doesn't contain passwords, I would argue that names and usernames are sensitive enough.

To solve these issues, what do you think about building some key from the used entry (like `folders+name+username`), hashing it and saving that to the file? When starting up, these entries need to be correlated to the ones from rbw, so there will definitely be a small performance hit, but I hope it's not noticeable.
In any case, there should be a parameter to toggle caching on or off (just like you already implemented).

What do you think?

**Comment by fdw** [comment]
One more thought: Should we do something similar for custom fields?

**Comment by fdw** [comment]
Awesome, thank you very much! I'm looking forward to it 🙂

**Pull request closed without merging**
