### PR TITLE
WIP: Changing help texts

### PR DESCRIPTION
**Pull request by tosti007**
This PR build further upon #48, hence the WIP and I'll fix this once that PR has been accepted or denied.

When calling `rbw-rofi` with an `--action` argument, the help message and alt-codes in rofi (`--mesg`) is unchanged. I think it would be neat to make these adaptive, such that the default action is not an alt-code.

In the case that the help message is not rendered, having it adaptive would be confusing (imo) and thus the list is then a fixed order: both, username, password, menu.

PS: this was my main motivation for PR #48.

### CODE REVIEW

**Comment by tosti007** [comment]
When I was writing the description of this PR I realized that not having the default action as an alt-code might be undesired by some users, hence I just added a commit that adds the default action at the end of the action list, but does not render this last action in the help message.

**Comment by fdw** [comment]
Hi @tosti007, I'd like to prepare a new release. If you think this this PR is still useful, can you either rebase it or drop me a note so that I can have look? Thank you 🙂

**Comment by tosti007** [comment]
Hey @fdw, I think it's best to release it without this PR. I do think it's usefull, but I am not sure if I have time to fix it before the release.

**Comment by fdw** [comment]
Hey @tosti007, how's it looking? 😉

**Comment by tosti007** [comment]
Haha sorry for the large delay, I saw the large update to 1.0.0 and found I didn't have the time at that moment to rebase. I have just fixed it. 
If you think this shouldn't be added, I'll probably extract some small changes from this PR to a new PR (such as the show_help arg), so don't worry about those.

**Comment by fdw** [comment]
Because we now support custom keybindings with correct, dynamic help texts, this PR isn't necessary anymore 🙂

**Pull request closed without merging**
