### PR TITLE
Add help text and change prompt name

### PR DESCRIPTION
**Pull request by DSIW**

### CODE REVIEW

**Comment by fdw** [comment]
Hey, thanks for your contribution! 🙂

I see the point of the help text, but, to be honest, I'm not a fan of it showing all the time. What do you think about making it configurable via a cli parameter (like `--show-help`)?

**Comment by DSIW** [comment]
Your welcome!

That's fine for me. I will have a look into this as soon as I have time for this.

**Comment by fdw** [comment]
Yeah, no hurry! If you want to, I can also have a look some time 🙂

**Comment by fdw** [comment]
As an inspiration, you can look how [`rofimoji`](https://github.com/fdw/rofimoji) implements configuration.

**Comment by fdw** [comment]
Hey @DSIW, I just wanted to ask if you've made progress or need help?

**Comment by fdw** [comment]
I have just pushed a major update that should fix this problem. Please open a ticket if you're missing anything 🙂

**Comment by DSIW** [comment]
Awesome! Thank you for taking care of it.

**Pull request closed without merging**
