### PR TITLE
Minor Credentials refactors

### PR DESCRIPTION
**Pull request by tosti007**
This PR moves some wrapper functions and removes function arguments in order to reduce the logic in `rofi_rbw.py` a bit.

### CODE REVIEW

**Comment by fdw** [comment]
Hey! As is expected for a refactoring, there are some changes I like and some that I don't (sorry). Most importantly, you inspired me to try and restructure `Entry` and `Credentials` a bit 🙂
But how should we proceed here? Should I work on your branch, adding my changes? Do you want to rework it so we can merge it before I add my refactorings? Or should I do everything in separate commits and list you as co-author?

**Comment by tosti007** [comment]
Haha no worries, these are mostly some changes that i thought might be nice.
I'd say do whatever is easiest for you! If your idea is substantially different from mine I think creating your own commits would be easier than continuing on this branch, but if you prefer to continue with this PR feel free to do so.

**Comment by fdw** [comment]
I've just pushed something... it escalated a bit, but I like the structure a lot more now. What do you think?

**Comment by tosti007** [comment]
Haha I think the reworks are great so I'll close this

**Pull request closed without merging**
